### ISSUE TITLE
Tabs or Windows

### ISSUE THREAD

**Issue by ResuIl** [warxander/vein-demo#1]
How Can i make 2 tab or 2 window ?

**Comment by warxander** [comment]
Multiple windows are not supported at the moment.

Tabs can be easily implemented with buttons, for example:
```lua
local tabs = {
  { name = 'Tab1', drawFunc = function() --[[Draw Tab1]] end },
  { name = 'Tab2', drawFunc = function() --[[Draw Tab2]] end },
  { name = 'Tab3', drawFunc = function() --[[Draw Tab3]] end },
}
local currentTabIndex = 1

-- Tab controls
vein:beginRow()
  for tabIndex, tab in ipairs(tabs) do
    if vein:button(tab.name) then currentTabIndex = tabIndex end
  end
vein:endRow()

-- Tab content
tabs[currentTabIndex].drawFunc()
```

**Comment by ResuIl** [comment]
> Multiple windows are not supported at the moment.
> 
> Tabs can be easily implemented with buttons, for example:
> 
> ```lua
> local tabs = {
>   { name = 'Tab1', drawFunc = function() --[[Draw Tab1]] end },
>   { name = 'Tab2', drawFunc = function() --[[Draw Tab2]] end },
>   { name = 'Tab3', drawFunc = function() --[[Draw Tab3]] end },
> }
> local currentTabIndex = 1
> 
> -- Tab controls
> vein:beginRow()
>   for tabIndex, tab in ipairs(tabs) do
>     if vein:button(tab.name) then currentTabIndex = tabIndex end
>   end
> vein:endRow()
> 
> -- Tab content
> tabs[currentTabIndex].drawFunc()
> ```

i cant do it. it close instant. can you send me demo.lua (With Tabs) which can i copy paste it and learn codes

**Comment by warxander** [comment]
No.
